[package]

name = "ws"
version = "0.1.0"
authors = ["John P Mayer Jr <john.p.mayer.jr@gmail.com>"]

[dependencies.rust-crypto]

git = "https://github.com/DaGenix/rust-crypto.git"

[lib]

name = "ws"

path = "src/lib.rs"